import { App, Component } from "vue";
import {
  ElTag,
  ElAffix,
  ElSkeleton,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElEmpty,
  ElScrollbar,
  ElSubMenu,
  ElButton,
  ElCol,
  ElRow,
  ElSpace,
  ElDivider,
  ElCard,
  ElDropdown,
  ElDialog,
  ElMenu,
  ElMenuItem,
  ElDropdownItem,
  ElDropdownMenu,
  ElIcon,
  ElInput,
  ElImage,
  ElForm,
  ElFormItem,
  ElLoading,
  ElLink,
  ElPopover,
  ElPopper,
  ElTooltip,
  ElTable,
  ElTableColumn,
  ElTabs,
  ElTabPane,
  ElDrawer,
  ElPagination,
  ElAlert,
  ElRadioButton,
  ElRadioGroup,
  ElDescriptions,
  ElDescriptionsItem,
  ElRadio,
  ElCheckbox,
  ElCheckboxGroup,
  ElSelect,
  ElOption,
  ElInfiniteScroll,
} from "element-plus";

const components = [
  ElTag,
  ElAffix,
  ElSkeleton,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElEmpty,
  ElScrollbar,
  ElSubMenu,
  ElButton,
  ElCol,
  ElRow,
  ElSpace,
  ElDivider,
  ElCard,
  ElDropdown,
  ElDialog,
  ElMenu,
  ElMenuItem,
  ElDropdownItem,
  ElDropdownMenu,
  ElIcon,
  ElInput,
  ElImage,
  ElForm,
  ElFormItem,
  ElLink,
  ElPopover,
  ElPopper,
  ElTooltip,
  ElTable,
  ElTableColumn,
  ElTabs,
  ElTabPane,
  ElDrawer,
  ElPagination,
  ElAlert,
  ElRadioButton,
  ElRadioGroup,
  ElDescriptions,
  ElDescriptionsItem,
  ElRadio,
  ElCheckbox,
  ElCheckboxGroup,
  ElSelect,
  ElOption
];

const plugins = [ElLoading, ElInfiniteScroll];

export function useElementPlus(app: App) {
  components.forEach((component: Component) => {
    app.component(component.name, component);
  });
  plugins.forEach(plugin => {
    app.use(plugin);
  });
}
